### ISSUE TITLE
Contao-Request-Klasse

### ISSUE THREAD

**Issue by Tastaturberuf** [christianbarkowsky/contao-tiny-compress-images#1]
Super Arbeit Christian!

Wieso nutzt du nicht einfach die Contao-Response-Klasse? Dann sparst du das ganze if-else-Zeugs. Auch würde ich nicht "Curl und nicht-Curl" unterscheiden, da gibts keine Vorteile.

Hab mal nen Dummy gebaut der super funktioniert.

``` php
$strUrl           = 'https://api.tinypng.com/shrink';
$strKey           = 'secretAPIkey';
$strAuthorization = 'Basic '.base64_encode("api:$strKey");

$objRequest         = new Request();
$objRequest->method = 'post';

// Müsste man hier nicht auch dynamisch png oder jpeg übergeben?
$objRequest->setHeader('Content-type', 'image/png');
$objRequest->setHeader('Authorization', $strAuthorization);

$objRequest->send($strUrl);

if ( !$objRequest->hasError() )
{
    // successful
}

dump(json_decode($objRequest->response));
dump($objRequest);
```

**Comment by christianbarkowsky** [comment]
Weil es schnell gehen musste. _hehe_
Guck ich mir aber an.

**Comment by Tastaturberuf** [comment]
Hab ich mir gedacht. Ich könnt nen PR basteln. :+1:

**Comment by christianbarkowsky** [comment]
Erledigt.

https://github.com/christianbarkowsky/contao-tiny-compress-images/blob/master/classes/TinyCompressImages.php

**Comment by Tastaturberuf** [comment]
Sieht doch schon viel besser aus :+1: 
Ist wahrscheinlich noch sinnvoll nach dem `file_put_contents` die Datenbank mit den Files zu aktualisieren:
`\Dbafs::addResource($file);` oder `\Dbafs::addResource($strFile);`

Theoretisch ändert sich ja der Hashwert. Ka ob das von Belang ist.

**Comment by christianbarkowsky** [comment]
Soooo ... neues Release.
Aber ohne addResource ... die resource ist ja schon da. :)

**Comment by Tastaturberuf** [comment]
~~Ja stimmt. Aber wenn der Filename mit md5 den Hash bildet, dann ändert sich da eh nix. Ich dachte der macht nen „richtigen“ Datei-Hash mit `hash_file()`.~~

Edit: Ich sollte den Code richtig lesen...`md5_file()`.

**Comment by Tastaturberuf** [comment]
Perfekt :+1:
