### ISSUE TITLE
Handle changed filename while uploading

### ISSUE THREAD

**Issue by Xirdion** [christianbarkowsky/contao-tiny-compress-images#11]
Hello. 
We really like your bundle because now each of our customers can have compressed files.
But we have found an issue.
We also use the [Sanitizer-Bundle](https://github.com/heimrichhannot/contao-filename-sanitizer-bundle) which can change the filename while uploading the files.
But if this happens, the Request to tinypng.com fails because there is no input file.

The reason is, that you are using the old file name, even so you already have the whole database object of the file.
Changing `$file` to `$objFile->path` would solve the problem.
https://github.com/christianbarkowsky/contao-tiny-compress-images/blob/9659393f7d21fee4659eab074b5462af4a0c4e07/src/classes/TinyCompressImages.php#L45

**Comment by christianbarkowsky** [comment]
Hey @Xirdion,

I've adapted the source code.
Please test the master with and without the Sanitizer-Bundle.

Merci.

**Comment by Xirdion** [comment]
Hey.

Thanks for the quick answer. I have tested your changes.
In both cases the module now works as expected, even if the filename changed. :+1:
