### ISSUE TITLE
Upload funktioniert nicht mehr

### ISSUE THREAD

**Issue by markaba** [christianbarkowsky/contao-tiny-compress-images#15]
Ist am 25.05.2020 aufgefallen: Der Upload in der Dateiverwaltung funktionier nicht mehr...

- es gibt das normale Häkchen auf dem Upload-Thumb
- im Log steht: "Compression was successful. (File: files/bilder/..."
-  in der Dateiverwaltung hat das Bild 0 byte und mit rotem Icon: "Broken image!"

Gibt es weitere Debug-Möglichkeiten?

Contao Version 4.9.3
contao-tiny-compress-images-Version: 1.0.7
![image](https://user-images.githubusercontent.com/1880101/82802637-7dfd2a00-9e7f-11ea-9482-41af75271c73.png)
![image](https://user-images.githubusercontent.com/1880101/82802726-a38a3380-9e7f-11ea-9161-7afdd22f3acf.png)

**Comment by christianbarkowsky** [comment]
Leider kann ich das Problem nicht nachstellen @markaba
