### ISSUE TITLE
Fehler nach "Chache der Entwicklungsumgebung leeren"

### ISSUE THREAD

**Issue by dp-designpilot** [christianbarkowsky/contao-tiny-compress-images#17]
Hallo Christian

**_Folgendes Problem tritt auf nach dem ich die Erweiterung installiert habe und danach den Cache geelert habe:_**

$ /opt/plesk/php/7.4/bin/php -q -dmax_execution_time=0 -dmemory_limit=-1 -dallow_url_fopen=1 -ddisable_functions= -ddate.timezone=Europe/Zurich /home/httpd/vhosts/murg-kultur.ch/httpdocs/web-wegmann-work/vendor/contao/manager-bundle/bin/contao-console cache:clear --env=dev --no-warmup

In ContaoKernel.php line 94:
                                                                               
  Notice: Undefined property: Contao\ManagerBundle\HttpKernel\ContaoKernel::$  
  rootDir                                                                      
                                                                               
Process terminated with exit code 1
Result: General error

**Comment by christianbarkowsky** [comment]
Hallo Didier @dp-designpilot,

ich kann hier nicht erkennen das meine Erweiterung das Problem ist.
Was steht in den Logs?

**Comment by dp-designpilot** [comment]
Hallo Christian

Das Problem rührt nicht von deiner Erweiterung, das ist glaube ich ein allgemeines Problem
https://github.com/contao/contao/pull/2774/files

Sorry das ich das auf deine Erweiterung geschoben habe

Grüsse
Didier
