### ISSUE TITLE
Dateikomprimierung schlägt fehl (No error).

### ISSUE THREAD

**Issue by design23** [christianbarkowsky/contao-tiny-compress-images#27]
Hi Christian,
erstmal großes Lob für diese sehr nützliche Erweiterung.
Bei einem aktuellen Projekt habe ich das Problem, dass keine Komprimierung stattfindet.
Ein frischer API key ist eingetragen und die Fehlermeldung besteht nur aus dieser Meldung:
**Dateikomprimierung files/content/Testbild.png fehlgeschlagen (No error).**

Es gibt keine weiteren Infos - auch die var/logs zeichnet nichts dazu auf.
Any ideas?

Contao 4.9.26
Erweiterung: 2.1.0

**Comment by christianbarkowsky** [comment]
@design23 wie groß ist das Bild?

**Comment by design23** [comment]
@christianbarkowsky Ich habe es mit allen möglichen Größen und Formaten versucht (von 50kb bis 10MB, jpg, jpeg, png). Die Logs schweigen sich aus.

**Comment by christianbarkowsky** [comment]
Wollen wir mal eine Bildschirmübertragung machen?

**Comment by design23** [comment]
Das geht aktuell leider nicht. 
Da ich momentan aber noch ein weiteres Projekt aufbaue, das Deine Extension auch verwendet und problemlos läuft, habe ich die beiden Installationen mal verglichen. Bei der funktionierenden Installation ist Version 1.1.0 im Einsatz und wird im CM auch als neueste Version deklariert. Bei der nicht funktionierenden Installation ist es Version 2.1.0.
Ich habe dort jetzt mal ein Downgrade auf 1.1.0 durchgeführt und die Sache läuft wieder. Vielleicht hilft das, das Problem etwas einzugrenzen.
