### ISSUE TITLE
Fehlermeldung in Dateiverwaltung bei Contao 4.12.6

### ISSUE THREAD

**Issue by green-pixelbox** [christianbarkowsky/contao-tiny-compress-images#28]
Danke erstmal für das super Modul. In Contao 4.9 funktioniert es einwandfrei, da nun die Contao 4.13 als neue LTS anliegt, erstelle ich neue Websites in contao 4.12 momentan. Die Modulinstallation funktioniert einwandfrei in C 4.12 im Manager, wenn man dann aber im Backend auf Dateiverwaltung klickt, kommt folgende Fehlermeldung siehe Screenshot.

**Comment by green-pixelbox** [comment]
![error-c412](https://user-images.githubusercontent.com/3920742/154262874-9d2e930c-d697-44db-a010-944c268e4efc.JPG)

**Comment by christianbarkowsky** [comment]
Danke für den Hinweis. Hast du den API Key unter Einstellungen hinterlegt? @green-pixelbox

**Comment by green-pixelbox** [comment]
wenn man den api key nicht hinterlegt hat, kommt die Fehlermeldung. Wenn man den Key aber eingegeben hat funktioniert alles. :) also alles halb so schlimm :) Danke für den Hinweis

**Comment by christianbarkowsky** [comment]
Wird trotzdem angepasst - werde das mit einem Info-Dialog abfangen.

**Comment by green-pixelbox** [comment]
super herzlichen Dank :)
