### ISSUE TITLE
Kompatibilität zu Contao 4.13 LTS?

### ISSUE THREAD

**Issue by mandrael** [christianbarkowsky/contao-tiny-compress-images#29]
Hi, ich finde hier keine Angaben zur Kompatibilität mit der neuen LTS. Läuft die Erweiterung mit v4.13 LTS?

**Comment by christianbarkowsky** [comment]
Hallo @mandrael,

selbst­ver­ständ­lich läuft Tiny-Compess unter Contao 4.13. Du kannst die Erweiterung bedenkenlos installieren und nutzen.
Ich werde die README um einen Kompatibilitätshinweis erweitern.
