### ISSUE TITLE
Feature-Request: Confirmation

### ISSUE THREAD

**Issue by ngdot** [christianbarkowsky/contao-tiny-compress-images#3]
Hi,
vorweg: Super Erweiterung, klappt super.

Mein Vorschlag wäre es eine Confirmation-Box nach der Kompression direkt in der Dateiverwaltung auszugeben. Bei erfolgreicher Kompression könnte man z.B. ausgeben: Kompression erfolgreich. Interessant wäre es dort zusätzlich noch den Compression-Count mit auszugeben. Dieser ist auch in der API vorhanden. Bei einem Fehler müsste man dann natürlich eine Warning-Box ausgeben.

Freue mich auf deine Rückmeldung!

Gruß

**Comment by christianbarkowsky** [comment]
Hi @Nico0o,

wird erledigt.

**Comment by ngdot** [comment]
Super cool, freut mich! 
Habe die Erweiterung bereits in vielen Live-Projekten eingebaut und bin sehr begeistert :)

**Comment by ngdot** [comment]
Die Error-Meldungen von TINY sollten ebenfalls mit ausgegeben werden. 
Beispiel: Wenn man ein CMYK .JPG hochladen will, fängt er an zu meckern. Im Backend bekommt man davon aber nichts mit :P

**Comment by ngdot** [comment]
Hi, gibt es hier etwas neues :) Nutze die Erweiterung auf fast jeder Seite, wäre schön wenn es hier ein Update geben würde!

**Comment by christianbarkowsky** [comment]
Hi @NicolasGoerlach ab KW43 habe ich etwas Zeit mich um dein Feature-Request zu kümmern.

**Comment by ngdot** [comment]
Super, freu mich drauf!

**Comment by christianbarkowsky** [comment]
Das hab ich hier wohl etwas schleifen lassen @ngdot! Packe ich in die neue Version.
