### ISSUE TITLE
Backend Fehler beim Hochladen von Bilder

### ISSUE THREAD

**Issue by berecont** [christianbarkowsky/contao-tiny-compress-images#31]
Bilder werden hochgeladen, jedoch nicht komprimiert.
» Upload via Dateimanager eines Bildes
» False-Icon erscheint - also jenes mit dem x nicht mit dem Häckchen
» Bild wird dabei wohl aber hochgeladen
» erneuter Klick auf das ausgegraute tinypng-Panda-Logo zum nochmaligen Komprimieren bringt Fehlermeldung mit Abbruch des Backend
`Attempted to load class "Path" from namespace "Webmozart\PathUtil". Did you forget a "use" statement for e.g. "Symfony\Component\Filesystem\Path", "ScssPhp\ScssPhp\Util\Path" or "BaconQrCode\Renderer\Path\Path"?`
Hat dies etwas mit dem #30 zu tun?

Contao 4.13.8
v 2.1.1 v 2.08.2022
last updated version yesterday | 28.08.2022

**Comment by Ernestopheles** [comment]
Nimm die neueste Version also 2.1.2, das hat bei mir diese Probleme gelöst.

**Comment by christianbarkowsky** [comment]
Hey Bernhard @berecont,
wie @Ernestopheles schon geschreiben hat - mit der 2.1.2 läuft wieder alles
