### ISSUE TITLE
500 Images Limit - was passiert danach?

### ISSUE THREAD

**Issue by JensB74** [christianbarkowsky/contao-tiny-compress-images#7]
Hallo,
zwar ist es mir bisher noch nicht passiert, dass ich an das 500 Bilder Limit gekommen wäre, aber mich würde trotzdem interessieren, was passiert? 
Auf der Webseite von Tiny steht: 

> When you reach your compression limit the API will return the error message: Your monthly limit has been exceeded.

**Bedeutet das, es gibt im Backend dann eine Fehlermeldung und man kann keine weiteren Bilder mehr hochladen?**

Vielleicht kann man diese Meldung abfangen und stattdessen für den Rest des Monats unkomprimiert weitermachen, diese Bilder werden dann "gemerkt" und im nächsten Monat nachträglich komprimiert.
Wer dauerhaft das Limit überschreitet, sollte natürlich bezahlen!

**Comment by christianbarkowsky** [comment]
Wenn das Limit erreicht ist, wird umkomprigmiert weitergemacht.
Durch #2 siehst man nun, ob einen Datei komprimiert wurde.
