### ISSUE TITLE
Vorhandene Bilder komprimieren

### ISSUE THREAD

**Issue by JensB74** [christianbarkowsky/contao-tiny-compress-images#8]
Das wäre auch noch super, wenn es einen Button/Link in der Dateiverwaltung gäbe, womit man schon vorhandene Bilder nachträglich komprimieren könnte.

Ist vielleicht nicht wichtig, aber nice-to-have: eine Meldung nach dem Upload, dass das Bild erfolgreich komprimiert wurde (es wird ja auch im Systemlog angezeigt, warum dann nicht auch beim Upload), dort könnte man auch prima dann anzeigen, wieviele Bilder man diesen Monat noch komprimieren kann.

**Comment by christianbarkowsky** [comment]
Done. Big thx to David Greminger @bytehead 🙇
