### ISSUE TITLE
Komprimierung der Bilder beim Upload

### ISSUE THREAD

**Issue by chriza** [christianbarkowsky/contao-tiny-compress-images#9]
Hallo,

ich habe in mehreren Installationen mit unterschiedlichen API-Keys festgestellt, daß Bilder beim Upload nicht mehr komprimiert werden.

**Comment by christianbarkowsky** [comment]
Hey @chriza,

tritt das Problem noch auf? Gibt es Fehlermeldungen? Ist das Limit erreicht?
